### ISSUE TITLE
Question: JSIL.InitializeType, __PreInitMembrane__, RunStaticConstructors

### ISSUE THREAD

**Issue by iskiselev** [sq/JSIL#904]
@kg, I need some consultation from you.
I still not understand, how __PreInitMembrane__ works and when it is created. I'm also not sure, why RunStaticConstructors for some type called from InitializeType and only before first instance created for others.
Why we can't rely on membranes for types, that initialized from JSIL.Initialize?

I'm trying to solve some issues with cycle in type constructions, but feels that I need some more info on questions that I've asked here.

**Comment by kg** [comment]
PreInitMembrane exists so that a type's static constructor runs when the type's members are first used. Otherwise, the static constructor would run when the type's public interface was first accessed, which is far too early and would cause cycles/stack overflows. It's basically a hack to approximate how static constructors work in .NET.

Membranes could probably be applied more universally. There are also some better solutions to type construction cycles possible but I've never been clear-minded enough to implement one without breaking everything.

**Comment by iskiselev** [comment]
In what cases type static ctor could be executed right from InitializeType (through call to `classObject.__PreInitMembrane__.maybeInit();`)?

**Comment by kg** [comment]
Before the introduction of the membrane, the only option was to run the cctor while creating the public interface, because after we created the public interface all the methods were accessible.

The membrane ensures that the methods aren't invoked until the cctor has run.

The correct fix for this is for ```asm.Namespace.Type``` to not expose the public interface, or something. That way all the cyclic dependencies and initialization order problems go away. That makes interop tough, though...

**Comment by kg** [comment]
Also, I misread your comment, and I have no idea how maybeInit could invoke the cctor. It's probably a bug, maybe it's invoking the membrane handler when creating a membrane...

**Comment by iskiselev** [comment]
Next question what is the purpose of next line inside `JSIL.InitializeType`:
```
      if (classObject.__PreInitMembrane__)
        classObject.__PreInitMembrane__.maybeInit();
      if (classObject.prototype && classObject.prototype.__PreInitMembrane__)
        classObject.prototype.__PreInitMembrane__.maybeInit();
```

This lines execute static ctors (for some classes).

**Comment by kg** [comment]
I really don't remember what that does. If I get some time I'll read through things again.

**Comment by iskiselev** [comment]
Thanks, will try to debug it a little bit more and to guess this myself :)

**Comment by iskiselev** [comment]
Calling type static constructor from `JSIL.InitializeType ` removed through PR #906.
